mixin: # 注意下面缩进
  dns:
    enable: true
    listen: :53
    nameserver:
      - 119.29.29.29
      - 114.114.114.114
      - 8.8.8.8
    fallback:
      - tls://8.8.8.8:853
      - 8.8.8.8
      - https://dns.google/dns-query
#      - https://dns.alidns.com/dns-query
